# Auto-label configuration
# Create corresponding labels in the repo (Settings > Labels) matching the keys below.
# Path-based labels
frontend:
  - 'src/app/**'
config:
  - 'biome.json'
  - 'tsconfig.json'
  - 'postcss.config.mjs'
  - '.vscode/**'
ci:
  - '.github/workflows/**'
  - '.github/labeler.yml'
docs:
  - 'README.md'
  - 'docs/**'
tests:
  - '__tests__/**'
  - 'playwright.config.ts'
  - 'vitest.config.ts'

# Fallback: label PRs touching only devDependencies changes in package.json
chore:
  - 'package.json'