# Auto-label configuration
frontend: 'src/app/**'
config:
  - 'biome.json'
  - 'tsconfig.json'
  - 'postcss.config.mjs'
  - '.vscode/**'
ci:
  - '.github/workflows/**'
  - '.github/labeler.yml'
docs:
  - 'README.md'
  - 'docs/**'
tests:
  - '__tests__/**'
  - 'playwright.config.ts'
  - 'vitest.config.ts'
chore: 'package.json'