# Auto-label configuration
# Create corresponding labels in the repo (Settings > Labels) matching the keys below.
# Path-based labels
frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/app/**'
config:
  - changed-files:
    - any-glob-to-any-file:
      - 'biome.json'
      - 'tsconfig.json'
      - 'postcss.config.mjs'
      - '.vscode/**'
ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/labeler.yml'
docs:
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'
      - 'docs/**'
tests:
  - changed-files:
    - any-glob-to-any-file:
      - '__tests__/**'
      - 'playwright.config.ts'
      - 'vitest.config.ts'

# Fallback: label PRs touching only devDependencies changes in package.json
chore:
  - 'package.json'